### ISSUE TITLE
Error when running on ubuntu

### ISSUE THREAD

**Issue by ryan-4824** [cyberark/BlobHunter#11]
## Summary
Running this on WSL 2 using ubutnto 20.04. command used to run was python3 BlobHunter.py and sudo python3 BlobHunter.py
after installing requirements

Traceback (most recent call last):
  File "BlobHunter.py", line 19, in get_credentials
    stderr=subprocess.DEVNULL).decode("utf-8")
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'az account show --query user.name' returned non-zero exit status 127.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BlobHunter.py", line 222, in <module>
    main()
  File "BlobHunter.py", line 204, in main
    credentials = get_credentials()
  File "BlobHunter.py", line 22, in get_credentials
    subprocess.check_output("az login", shell=True, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)

**Comment by DanielNiv** [comment]
Hi @ryan-4824, 
Did you install Azure CLI on the Ubuntu machine?
