### ISSUE TITLE
Script breaks if there are inactive subscriptions

### ISSUE THREAD

**Issue by pravinsingh** [cyberark/BlobHunter#12]
## Summary
When we delete a subscription, it still keeps showing up as deleted/inactive state for the next 90 days. If there are such subscriptions present in the tenant, the script breaks .

## Steps to Reproduce
1. Create a test subscription in Azure
2. Delete the subscription. Notice that it still keeps showing up with Status as 'Disabled'
3. Run the script
4. We get this error:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/pravsing/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/pravsing/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/Users/pravsing/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 262, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 95, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/pravsing/Documents/Projects/Azure/BlobHunter/BlobHunter.py", line 227, in <module>
    main()
  File "/Users/pravsing/Documents/Projects/Azure/BlobHunter/BlobHunter.py", line 220, in main
    check_subscription(tenants_ids[i], tenants_names[i], subs_ids[i], subs_names[i], credentials)
  File "/Users/pravsing/Documents/Projects/Azure/BlobHunter/BlobHunter.py", line 78, in check_subscription
    resource_groups = [group.name for group in list(group_list)]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/azure/mgmt/resource/resources/v2020_06_01/operations/_resource_groups_operations.py", line 584, in get_next
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/azure/core/exceptions.py", line 102, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: (SubscriptionNotFound) The subscription 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx' could not be found.

## Reproducible
   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible

**Comment by pravinsingh** [comment]
I was able to debug and fix this. If someone could review and merge my earlier PR (#9), I would create a new PR for this fix.

**Comment by yanivyakobovich** [comment]
Your pull request has been accepted. This issue is now resolved.
