### ISSUE TITLE
Script doesnt work if there is no blob endpoint

### ISSUE THREAD

**Issue by fontvu** [cyberark/BlobHunter#15]
## Summary
Script breaks if there is no blob endpoint in storage account.
## Steps to Reproduce
1. Create a subscription with storage accounts
2. Leave some storage accounts without blob endpoint (only file endpoint etc)
3. Run the scripts
4. Error thrown

## Actual Results (including error logs, if applicable)
Traceback (most recent call last):
  File ".\BlobHunter.py", line 229, in <module>
    main()
  File ".\BlobHunter.py", line 222, in main
    check_subscription(tenants_ids[i], tenants_names[i], subs_ids[i], subs_names[i], credentials)
  File ".\BlobHunter.py", line 110, in check_subscription
    public_containers = check_storage_account(account, key)
  File ".\BlobHunter.py", line 60, in check_storage_account
    for cont in containers:
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\core\paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\core\paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\storage\blob\_models.py", line 402, in _get_next_cb
    use_location=self.location_mode)
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\storage\blob\_generated\operations\_service_operations.py", line 356, in list_containers_segment
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\core\pipeline\_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more times]
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 158, in send
    response = self.next.send(request)
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\storage\blob\_shared\policies.py", line 515, in send
    raise err
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\storage\blob\_shared\policies.py", line 489, in send
    response = self.next.send(request)
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\storage\blob\_shared\policies.py", line 290, in send
    response = self.next.send(request)
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\core\pipeline\_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "C:\Users\xxxxxxx\Desktop\blobhunt\lib\site-packages\azure\core\pipeline\transport\_requests_basic.py", line 261, in send
    raise error
azure.core.exceptions.ServiceRequestError: <urllib3.connection.HTTPSConnection object at 0x000002410ACAB198>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

## Environment setup
Azure account with Storage Account Contributor permission
Windows Server 2016

##Additional information
I suspect the error caused because the script tries to request to invalid URI. The getaddrinfo indicates no DNS record for the URI. I double checked by directly accessing the URI in web browser.

**Comment by fontvu** [comment]
Ok I can confirm the issue related to invalid blob URL. The `ENDPOINT_URL = '{}.blob.core.windows.net'` can be validated by matching with `az storage account show -n my-storage-account-name -g my-resource-group --query "primaryEndpoints.blob"` command from Azure-CLI.

**Comment by fontvu** [comment]
Ok I somehow fixed it by verifying (kinda) the URI with az storage account show -n

**Comment by yanivyakobovich** [comment]
Resolved.
