### ISSUE TITLE
Error on Kali Linux: get_credentials non-zero exit status

### ISSUE THREAD

**Issue by winklerrr** [cyberark/BlobHunter#19]
## Summary

When running the BlobHunter on Kali Linux 2022.3, after logging into Azure, the script execution fails.

```
Traceback (most recent call last):
  File "/home/kali/Desktop/scripts/azure/BlobHunter/BlobHunter.py", line 21, in get_credentials
    username = subprocess.check_output("az account show --query user.name", shell=True,
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'az account show --query user.name' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Desktop/scripts/azure/BlobHunter/BlobHunter.py", line 293, in <module>
    main()
  File "/home/kali/Desktop/scripts/azure/BlobHunter/BlobHunter.py", line 273, in main
    credentials = get_credentials()
  File "/home/kali/Desktop/scripts/azure/BlobHunter/BlobHunter.py", line 25, in get_credentials
    subprocess.check_output("az login", shell=True, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'az login' returned non-zero exit status 1.
```

`azure-cli` was installed via:

1. `sudo apt -y install azure-cli`
2.  the official install how-to <https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-2-step-by-step-installation-instructions>

**Comment by winklerrr** [comment]
After running `az login` manually, an error message was displayed, that my tenant has MFA turned on and I need to login via `az login --tenant TENANT_ID`. After doing that and restarting `BlobHunter`, it worked.
