### ISSUE TITLE
Problem get credentials

### ISSUE THREAD

**Issue by basziee** [cyberark/BlobHunter#2]
I can't get it to work. I got the following error's

`Traceback (most recent call last):
  File "C:\BlobHunter-main\BlobHunter.py", line 18, in get_credentials
    username = subprocess.check_output("az account show --query user.name", shell=True,
  File "C:\Users\schni\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\schni\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'az account show --query user.name' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\BlobHunter-main\BlobHunter.py", line 222, in <module>
    main()
  File "C:\BlobHunter-main\BlobHunter.py", line 204, in main
    credentials = get_credentials()
  File "C:\BlobHunter-main\BlobHunter.py", line 22, in get_credentials
    subprocess.check_output("az login", shell=True, stderr=subprocess.DEVNULL)
  File "C:\Users\schni\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\schni\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'az login' returned non-zero exit status 1.
PS C:\BlobHunter-main>`

**Comment by mediapirate** [comment]
You have to download and install Azure CLI for Windows, install it, close out of Git, re-open Git and then it should work.
