### ISSUE TITLE
Error starting script on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Damianoux** [cyberark/BlobHunter#20]
$ az --version
azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/damiano/.azure/cliextensions'

Python (Linux) 3.11.5 (main, Nov  8 2023, 05:21:25) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

$ python3.8 BlobHunter.py 

Traceback (most recent call last):
  File "BlobHunter.py", line 7, in <module>
    from azure.mgmt.resource import SubscriptionClient, ResourceManagementClient
  File "/home/damiano/.local/lib/python3.8/site-packages/azure/mgmt/resource/__init__.py", line 9, in <module>
    from .managedapplications import ApplicationClient
  File "/home/damiano/.local/lib/python3.8/site-packages/azure/mgmt/resource/managedapplications/__init__.py", line 9, in <module>
    from ._application_client import ApplicationClient
  File "/home/damiano/.local/lib/python3.8/site-packages/azure/mgmt/resource/managedapplications/_application_client.py", line 12, in <module>
    from msrest import Deserializer, Serializer
  File "/home/damiano/.local/lib/python3.8/site-packages/msrest/__init__.py", line 28, in <module>
    from .configuration import Configuration
  File "/home/damiano/.local/lib/python3.8/site-packages/msrest/configuration.py", line 38, in <module>
    from .universal_http.requests import (
  File "/home/damiano/.local/lib/python3.8/site-packages/msrest/universal_http/__init__.py", line 53, in <module>
    from ..exceptions import ClientRequestError, raise_with_traceback
  File "/home/damiano/.local/lib/python3.8/site-packages/msrest/exceptions.py", line 31, in <module>
    from azure.core.exceptions import SerializationError, DeserializationError
ImportError: cannot import name 'SerializationError' from 'azure.core.exceptions' (/home/damiano/.local/lib/python3.8/site-packages/azure/core/exceptions.py)

**Comment by DanielNiv** [comment]
Hi @Damianoux,

First of all, 
have you installed all the requirements listed in the `requirements.txt` file?

Additionally, could you please provide information on the versions of the `msrest` and `azure-core` libraries installed in your environment? 
You can check this using the following command:

```bash
pip3 show msrest azure-core

Thanks!
