### ISSUE TITLE
This request is not authorized to perform this operation

### ISSUE THREAD

**Issue by mdaslamansari** [cyberark/BlobHunter#8]
Hi,

I am owner of the subscription and still I am getting below error -

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/azure/storage/blob/_models.py", line 399, in _get_next_cb
    use_location=self.location_mode)
  File "/usr/local/lib/python3.7/dist-packages/azure/storage/blob/_generated/operations/_service_operations.py", line 336, in list_containers_segment
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'This request is not authorized to perform this operation.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BlobHunter.py", line 222, in <module>
    main()
  File "BlobHunter.py", line 215, in main
    check_subscription(tenants_ids[i], tenants_names[i], subs_ids[i], subs_names[i], credentials)
  File "BlobHunter.py", line 103, in check_subscription
    public_containers = check_storage_account(account, key)
  File "BlobHunter.py", line 56, in check_storage_account
    for cont in containers:
  File "/usr/local/lib/python3.7/dist-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/usr/local/lib/python3.7/dist-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/usr/local/lib/python3.7/dist-packages/azure/storage/blob/_models.py", line 401, in _get_next_cb
    process_storage_error(error)
  File "/usr/local/lib/python3.7/dist-packages/azure/storage/blob/_shared/response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.HttpResponseError: This request is not authorized to perform this operation.

**Comment by DanielNiv** [comment]
Hi @mdaslamansari,
Can you please share the Blob Storage actions that your account can perform?

**Comment by pravinsingh** [comment]
@mdaslamansari I too faced the same issue earlier. It happens if some of the containers in your storage account have further restrictions which stop you from accessing it (_e.g._ allowing access only from certain IPs and your IP is not in that list). You can verify this from the Azure portal. Trying to open such containers from the portal will show the same error.

@DanielNiv I've created a PR with the fix (which is basically just adding exception handling to the function check_storage_account). Can you please review and merge?

**Comment by mdaslamansari** [comment]
Thanks. I am also getting below timeout error -

azure.core.exceptions.ServiceRequestError: (<urllib3.connection.HTTPSConnection object at 0x7f51db93aef0>, 'Connection to xxxxxxx.blob.core.windows.net timed out. (connect timeout=20)')

**Comment by fontvu** [comment]
> @mdaslamansari I too faced the same issue earlier. It happens if some of the containers in your storage account have further restrictions which stop you from accessing it (_e.g._ allowing access only from certain IPs and your IP is not in that list). You can verify this from the Azure portal. Trying to open such containers from the portal will show the same error.
> 
> @DanielNiv I've created a PR with the fix (which is basically just adding exception handling to the function check_storage_account). Can you please review and merge?

It also happens if there is the managed storage account in your subscription i.e. Azure Databricks resource.
